"""Implementação de novas tabelas

Revision ID: d24f201fc294
Revises: f5e85ec138eb
Create Date: 2026-09-16 09:09:16.011994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24f201fc294'
down_revision: Union[str, Sequence[str], None] = 'f5e85ec138eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_disciplina', sa.String(length=255), nullable=False),
    sa.Column('carga', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome_aluno', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['tb_enderecos.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('tb_notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['tb_alunos.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disciplina_id'], ['tb_disciplinas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_notas')
    op.drop_table('tb_alunos')
    op.drop_table('tb_disciplinas')
    # ### end Alembic commands ###
