"""Criacao da tabela tb_endereco

Revision ID: dbf6576fb4b5
Revises: 
Create Date: 2026-09-09 11:06:00.081576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf6576fb4b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('Endereco', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cep')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_enderecos')
    # ### end Alembic commands ###
