"""Implementação das novas tabelas

Revision ID: e12c973be182
Revises: d24f201fc294
Create Date: 2026-09-16 09:13:00.148271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12c973be182'
down_revision: Union[str, Sequence[str], None] = 'd24f201fc294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_alunos', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tb_alunos', 'endereco_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('tb_alunos_endereco_id_fkey'), 'tb_alunos', type_='foreignkey')
    op.create_foreign_key(None, 'tb_alunos', 'tb_enderecos', ['endereco_id'], ['id'])
    op.alter_column('tb_notas', 'nota',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.drop_constraint(op.f('tb_notas_disciplina_id_fkey'), 'tb_notas', type_='foreignkey')
    op.drop_constraint(op.f('tb_notas_aluno_id_fkey'), 'tb_notas', type_='foreignkey')
    op.create_foreign_key(None, 'tb_notas', 'tb_disciplinas', ['disciplina_id'], ['id'])
    op.create_foreign_key(None, 'tb_notas', 'tb_alunos', ['aluno_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_notas', type_='foreignkey')
    op.drop_constraint(None, 'tb_notas', type_='foreignkey')
    op.create_foreign_key(op.f('tb_notas_aluno_id_fkey'), 'tb_notas', 'tb_alunos', ['aluno_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('tb_notas_disciplina_id_fkey'), 'tb_notas', 'tb_disciplinas', ['disciplina_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('tb_notas', 'nota',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.drop_constraint(None, 'tb_alunos', type_='foreignkey')
    op.create_foreign_key(op.f('tb_alunos_endereco_id_fkey'), 'tb_alunos', 'tb_enderecos', ['endereco_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('tb_alunos', 'endereco_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tb_alunos', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
