"""Alteração tb_endereço

Revision ID: f5e85ec138eb
Revises: dbf6576fb4b5
Create Date: 2026-09-16 08:56:16.842468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e85ec138eb'
down_revision: Union[str, Sequence[str], None] = 'dbf6576fb4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_enderecos', sa.Column('endereco', sa.String(length=255), nullable=False))
    op.add_column('tb_enderecos', sa.Column('bairro', sa.String(length=50), nullable=False))
    op.add_column('tb_enderecos', sa.Column('cidade', sa.String(length=100), nullable=False))
    op.add_column('tb_enderecos', sa.Column('estado', sa.String(length=50), nullable=False))
    op.add_column('tb_enderecos', sa.Column('regiao', sa.String(length=50), nullable=False))
    op.drop_column('tb_enderecos', 'Endereco')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_enderecos', sa.Column('Endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('tb_enderecos', 'regiao')
    op.drop_column('tb_enderecos', 'estado')
    op.drop_column('tb_enderecos', 'cidade')
    op.drop_column('tb_enderecos', 'bairro')
    op.drop_column('tb_enderecos', 'endereco')
    # ### end Alembic commands ###
